export const ATTENDEES_SEND_RSVP = 'SEND_RSVP';
export const UPDATE_STATE = 'UPDATE_STATE';
export const LIVE_RESULT_SUBMITTED = "LIVE_RESULT_SUBMITTED";
export const LIVE_QUESTION_ACTIVATE = "LIVE_QUESTION_ACTIVATE";
export const LIVE_QUESTION_INACTIVE = "LIVE_QUESTION_INACTIVE";
